name: Releases

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        artifacts: '**/target/org.jhotdraw.*.jar'
        replacesArtifacts: false
        tag: $GITHUB_SHA
        name: Release $GITHUB_SHA
        body: Commit $GITHUB_SHA
